### ISSUE TITLE
npm start fails on Windows

### ISSUE THREAD

**Issue by tomeraz** [css-modules/browserify-demo#3]
Can you make this work on Windows?
I trying using cmd and github bash.
Output below.
10x!

$ npm start

> browserify-demo@1.0.1 start d:\temp\local-css\browserify-demo
> npm run build && http-server dist
> 
> browserify-demo@1.0.1 build d:\temp\local-css\browserify-demo
> npm run clean && npm run copy && npm run browserify
> 
> browserify-demo@1.0.1 clean d:\temp\local-css\browserify-demo
> rm -rf dist && mkdir dist
> 
> browserify-demo@1.0.1 copy d:\temp\local-css\browserify-demo
> cp src/index.html dist/index.html
> 
> browserify-demo@1.0.1 browserify d:\temp\local-css\browserify-demo
> browserify -t css-modulesify -o dist/index.js src/index.js

{ [Error: ENOENT, open 'd:\temp\local-css\browserify-demo\src\components\4-CompositionOverrides\shared\styles\layout.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'd:\temp\local-css\browserify-demo\src\components\4-CompositionOverrides\shared\styles\layout.css' }
{ [Error: ENOENT, open 'd:\temp\local-css\browserify-demo\src\components\4-CompositionOverrides\shared\styles\typography.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'd:\temp\local-css\browserify-demo\src\components\4-CompositionOverrides\shared\styles\typography.css' }
{ [Error: ENOENT, open 'd:\temp\local-css\browserify-demo\src\components\5-ScopedAnimations\shared\styles\animations.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'd:\temp\local-css\browserify-demo\src\components\5-ScopedAnimations\shared\styles\animations.css' }
{ [Error: ENOENT, open 'd:\temp\local-css\browserify-demo\src\components\3-ClassComposition\shared\styles\layout.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'd:\temp\local-css\browserify-demo\src\components\3-ClassComposition\shared\styles\layout.css' }
{ [Error: ENOENT, open 'd:\temp\local-css\browserify-demo\src\components\3-ClassComposition\shared\styles\typography.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'd:\temp\local-css\browserify-demo\src\components\3-ClassComposition\shared\styles\typography.css' }
{ [Error: ENOENT, open 'd:\temp\local-css\browserify-demo\src\components\3-ClassComposition\shared\styles\layout.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'd:\temp\local-css\browserify-demo\src\components\3-ClassComposition\shared\styles\layout.css' }
{ [Error: ENOENT, open 'd:\temp\local-css\browserify-demo\src\components\3-ClassComposition\shared\styles\typography.css']
  errno: -4058,
  code: 'ENOENT',
  path: 'd:\temp\local-css\browserify-demo\src\components\3-ClassComposition\shared\styles\typography.css' }
Starting up http-server, serving dist on: http://0.0.0.0:8080
Hit CTRL-C to stop the server

**Comment by joshgillies** [comment]
Hey @tomeraz, could you try running the [JSPM demo](https://github.com/css-modules/jspm-demo) to see whether you experience similar issues?

**Comment by kumorko** [comment]
also have problem to run it (Windows 7)

$ npm start

> browserify-demo@1.0.1 start c:\development\browserify-demo
> npm run clean && npm run copy && npm run budo
> 
> browserify-demo@1.0.1 clean c:\development\browserify-demo
> rm -rf dist && mkdir dist
> 
> browserify-demo@1.0.1 copy c:\development\browserify-demo
> cp src/index.html dist/index.html && cp src/components/0-Logo/logo.svg dist/lo
> go.svg
> 
> browserify-demo@1.0.1 budo c:\development\browserify-demo
> budo src/index.js:index.js --dir=dist -- -t babelify -t brfs -p [css-modulesif
> y -u postcss-modules-local-by-default -u postcss-modules-extract-imports -u post
> css-modules-scope -u postcss-color-rebeccapurple -u autoprefixer --autoprefixer.
> browsers '> 5%' -o dist/main.css] | opnr | garnish

Unknown browser query `'`
Unknown browser query `'`
Unknown browser query `'`
Unknown browser query `'`
Unknown browser query `'`
Unknown browser query `'`
Unknown browser query `'`
Unknown browser query `'`
Unknown browser query `'`

**Comment by toly-k** [comment]
Windows doesn't like single quote, so it worked after replacing `'> 5%'`  with `\"> 5%\"` in package.json
