### ISSUE TITLE
Do we must to add <link /> in the html <head /> to import css file?

### ISSUE THREAD

**Issue by wwayne** [css-modules/browserify-demo#4]
First of all, thanks for this awesome plugin : )

Actually, I wanted to use css-module in my independent react component which install and import via `npm` and `browerify`, now my component needs the user to import both js and css file, so I hope there is a way to `insert` css into js, so the users only need to import my js file. Do you think the css-modules can satisfy my requirements?

And I've noticed that the css-modules can insert css into html <head />, but it can't match the transformed css class on html nodes which for example is like `_src_components_App__hr`, so maybe insert transformed css class into html <head /> can works for me, but I don't know how to implement it ...

**Comment by joshwnj** [comment]
Hi @wwayne, at the moment `css-modulesify` writes generated css out to a file and you need to `<link />` it. There's no reason you couldn't do this all in js, that's just the most common use case.

**Comment by wwayne** [comment]
@joshwnj  Thanks : )
